"""add_delivery_log_and_retry_fields

Revision ID: 2b3c4a43c24d
Revises: b5d9ef5094d3
Create Date: 2026-02-09 16:09:40.048752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b3c4a43c24d'
down_revision: Union[str, Sequence[str], None] = 'b5d9ef5094d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spin_result_id', sa.Integer(), nullable=False),
    sa.Column('phase', sa.Integer(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('reward_type', sa.String(length=50), nullable=False),
    sa.Column('recipient', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('transaction_ref', sa.String(length=255), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['spin_result_id'], ['spin_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_logs_id'), 'delivery_logs', ['id'], unique=False)
    op.create_index(op.f('ix_delivery_logs_spin_result_id'), 'delivery_logs', ['spin_result_id'], unique=False)
    op.add_column('spin_results', sa.Column('phase1_attempts', sa.Integer(), nullable=False))
    op.add_column('spin_results', sa.Column('phase2_attempts', sa.Integer(), nullable=False))
    op.add_column('spin_results', sa.Column('max_retries', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spin_results', 'max_retries')
    op.drop_column('spin_results', 'phase2_attempts')
    op.drop_column('spin_results', 'phase1_attempts')
    op.drop_index(op.f('ix_delivery_logs_spin_result_id'), table_name='delivery_logs')
    op.drop_index(op.f('ix_delivery_logs_id'), table_name='delivery_logs')
    op.drop_table('delivery_logs')
    # ### end Alembic commands ###
