"""add_split_delivery_fields

Revision ID: b5d9ef5094d3
Revises: 433adde24377
Create Date: 2026-02-09 16:02:56.081338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5d9ef5094d3'
down_revision: Union[str, Sequence[str], None] = '433adde24377'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spin_results', sa.Column('total_value', sa.Integer(), nullable=False))
    op.add_column('spin_results', sa.Column('phase1_delivered', sa.Boolean(), nullable=False))
    op.add_column('spin_results', sa.Column('phase1_value', sa.Integer(), nullable=False))
    op.add_column('spin_results', sa.Column('phase1_delivered_at', sa.DateTime(), nullable=True))
    op.add_column('spin_results', sa.Column('phase1_scheduled_at', sa.DateTime(), nullable=True))
    op.add_column('spin_results', sa.Column('phase2_delivered', sa.Boolean(), nullable=False))
    op.add_column('spin_results', sa.Column('phase2_value', sa.Integer(), nullable=False))
    op.add_column('spin_results', sa.Column('phase2_delivered_at', sa.DateTime(), nullable=True))
    op.add_column('spin_results', sa.Column('phase2_scheduled_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spin_results', 'phase2_scheduled_at')
    op.drop_column('spin_results', 'phase2_delivered_at')
    op.drop_column('spin_results', 'phase2_value')
    op.drop_column('spin_results', 'phase2_delivered')
    op.drop_column('spin_results', 'phase1_scheduled_at')
    op.drop_column('spin_results', 'phase1_delivered_at')
    op.drop_column('spin_results', 'phase1_value')
    op.drop_column('spin_results', 'phase1_delivered')
    op.drop_column('spin_results', 'total_value')
    # ### end Alembic commands ###
